name:  Checks for terraform files

on:
  push:
    branches:
      - "*"

jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:

      - name: checkout
        uses: actions/checkout@v3.2.0

#      - name: configure-aws-credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-region: eu-west-2

      - name: setup-terraform
        uses: hashicorp/setup-terraform@v2

      - name: terraform fmt
        run: terraform fmt -recursive -check -diff

      - name: terraform-init
        run: terraform init #-backend-config=bucket=${{ secrets.TERRAFORM_STATE_BUCKET }} -backend-config=key=${{ secrets.TERRAFORM_STATE_KEY }} -backend-config=dynamodb_table=${{ secrets.TERRAFORM_STATE_DYNAMODB_TABLE }}

      - name: terraform-validate
        run: terraform validate -no-color

      - name: run tfsec
        run: |
          wget -q https://github.com/aquasecurity/tfsec/releases/download/v1.28.1/tfsec-linux-amd64
          mv tfsec-linux-amd64 tfsec
          chmod 755 ./tfsec
          ./tfsec --version
          ./tfsec

      - uses: actions/cache@v2
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

      - name: terraform-plan
        run: terraform plan -lock=false -no-color -input=false -out=tfplan

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: run-checkov
        run: |
          pip install --upgrade pip
          pip install --upgrade checkov
          terraform show -json tfplan  > tfjson
          checkov --directory ./
          checkov -f tfjson
